Card.create(rarity: "Common", group: "Car", value: 1, name: "1984 Yugo 55 GLS", text: "The worst car in history? I’m just trying to get to work.", image: "images/Car01.png")
Card.create(rarity: "Uncommon", group: "Car", value: 9, name: "2019 Toyota Prius", text: "I bet he’s wishing he had a hybrid, right? 60 miles to the gallon in the city.", image: "images/Car02.png")
Card.create(rarity: "Rare", group: "Car", value: 18, name: "2020 BMW 8 Series", text: "You can stick a BMW badge on a dead cat and people would still buy it.", image: "images/Car03.png")
Card.create(rarity: "Epic", group: "Car", value: 27, name: "Lamborghini Huracan Evo", text: "Owning a Lamborghini just makes you better than everyone else.", image: "images/Car04.png")
Card.create(rarity: "Legendary", group: "Car", value: 50, name: "1982 DeLorean", text: "Roads? Where we’re going we don’t need roads.", image: "images/Car05.png")
Card.create(rarity: "Common", group: "Computer", value: 1, name: "Compaq Portable", text: "Oh yeah? Well this baby has 128KB of RAM.", image: "images/Computer01.png")
Card.create(rarity: "Uncommon", group: "Computer", value: 6, name: "Dell Inspiron 7000", text: "Dude, you’re getting a Dell.", image: "images/Computer02.png")
Card.create(rarity: "Rare", group: "Computer", value: 19, name: "Apple iMac 27in", text: "Good artists copy; great artists steal.", image: "images/Computer03.png")
Card.create(rarity: "Epic", group: "Computer", value: 29, name: "8Pack Orion X2", text: "34,505 points in Geekbench's multi-core benchmark.  Nuff said.", image: "images/Computer04.png")
Card.create(rarity: "Legendary", group: "Computer", value: 48, name: "MU-TH-UR 6000", text: "I admire its purity. A survivor. Unclouded by conscience, remorse, or delusions of morality.", image: "images/Computer05.png")
Card.create(rarity: "Common", group: "House", value: 2, name: "Van Down by the River", text: "I'm gonna go out there and grab the world by the tail! And wrap it around and pull it down and put it in my pocket.", image: "images/House01.png")
Card.create(rarity: "Uncommon", group: "House", value: 8, name: "Modern Farmhouse", text: "The ideal home: big enough for you to hear the children, but not very well.", image: "images/House02.png")
Card.create(rarity: "Rare", group: "House", value: 15, name: "Cabin in the Woods", text: "I think it's pointless for a human to paint scenes of nature when they can go outside and stand in it.", image: "images/House03.png")
Card.create(rarity: "Epic", group: "House", value: 23, name: "Victorian Mansion", text: "My house is a reflection of who I am as a person...wealthy.", image: "images/House04.png")
Card.create(rarity: "Legendary", group: "House", value: 35, name: "Hobbit Hole", text: "It is no bad thing to celebrate a simple life.", image: "images/House05.png")
Card.create(rarity: "Common", group: "Pet", value: 2, name: "Naked Mole Rat", text: "Hairless and ugly? Yes please.", image: "images/Pet01.png")
Card.create(rarity: "Uncommon", group: "Pet", value: 8, name: "Labrador Retriever", text: "Who is a good boy? You’re a good boy!", image: "images/Pet02.png")
Card.create(rarity: "Rare", group: "Pet", value: 15, name: "African Grey Parrot", text: "A cracker? I’d prefer a cold one.", image: "images/Pet03.png")
Card.create(rarity: "Epic", group: "Pet", value: 29, name: "Siberian Tiger", text: "We tigers prefer to inflict excitement on others.", image: "images/Pet04.png")
Card.create(rarity: "Legendary", group: "Pet", value: 41, name: "Gizmo", text: "You look hungry, buddy? Are you hungry?", image: "images/Pet05.png")
Card.create(rarity: "Common", group: "Phone", value: 3, name: "Motorola Dynatac 8000X", text: "Hello!? Can you hear me now?", image: "images/Phone01.png")
Card.create(rarity: "Uncommon", group: "Phone", value: 6, name: "Motorola Razr V3", text: "My cell phone is my best friend. It’s my lifeline to the outside world.", image: "images/Phone02.png")
Card.create(rarity: "Rare", group: "Phone", value: 17, name: "Google Pixel 5", text: "Actually, Android is the superior phone OS.", image: "images/Phone03.png")
Card.create(rarity: "Epic", group: "Phone", value: 26, name: "Diamond Crypto Smartphone", text: "The phone of choice for Russian oligarchs and the hideously wealthy.", image: "images/Phone04.png")
Card.create(rarity: "Legendary", group: "Phone", value: 39, name: "Communicator", text: "One to beam up.", image: "images/Phone05.png")